#!/bin/bash

mkdir -p $HOME/Documents/Downloads $HOME/Pictures/Downloads $HOME/Videos/Downloads $HOME/Music/Downloads

documents_extension=("doc" "docx" "dotx" "pdf" "ppt" "ppsx" "pptm" "sldx" "sldm" "txt" "rar" "tmp" "zip")
pictures_extension=("png" "jpeg" "gif" "jpg" "psd")
video_extension=("mp4" "avi" "flv" "mov" "mpeg" "vob" "wms")
music_extension=("aac" "adt" "adts" "aif" "aifc" "aiff" "avi" "m4a" "mp3" "wav" "wma")

file_count=0
file_moved=0

sort_files() {
    for item in "$1"/*; do
        if [ -f "$item" ]; then
            ((file_count++))
            extension="${item##*.}"
            if [[ " ${documents_extension[*]} " == *" $extension "* ]]; then
                cp $item $HOME/Documents/Downloads
                ((file_moved++))
            elif [[ " ${pictures_extension[*]} " == *" $extension "* ]]; then
                cp $item $HOME/Pictures/Downloads
                ((file_moved++))
            elif [[ " ${video_extension[*]} " == *" $extension "* ]]; then
                cp $item $HOME/Videos/Downloads
                ((file_moved++))
            elif [[ " ${music_extension[*]} " == *" $extension "* ]]; then
                cp $item $HOME/Music/Downloads
                ((file_moved++))
            fi
        elif [ -d "$item" ]; then
            sort_files "$item"
        fi
    done
}

start_time=$(date +%s)
sort_files "$HOME/Downloads"
end_time=$(date +%s)

echo "Total files : $file_count done in $((end_time - start_time))s."
echo "$file_moved files moved."
